//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fifa19.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DireccionxFuncionario
    {
        public decimal codigoFuncionario { get; set; }
        public decimal codigoDireccion { get; set; }
        public string Pais { get; set; }
        public string estado { get; set; }
        public string ciudad { get; set; }
        public string distrito { get; set; }
        public string calle { get; set; }
        public string direccionExacta { get; set; }
        public string usuarioCreacion { get; set; }
        public string usuarioModificacion { get; set; }
        public System.DateTime fchCreacion { get; set; }
        public Nullable<System.DateTime> fchModificacion { get; set; }
    
        public virtual Funcionario Funcionario { get; set; }
    }
}
