//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fifa19.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcionario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Funcionario()
        {
            this.Contrato = new HashSet<Contrato>();
            this.CorreoxFuncionario = new HashSet<CorreoxFuncionario>();
            this.DireccionxFuncionario = new HashSet<DireccionxFuncionario>();
            this.FuncionarioXClubXTorneo = new HashSet<FuncionarioXClubXTorneo>();
            this.Oferta = new HashSet<Oferta>();
            this.TelefonoxFuncionario = new HashSet<TelefonoxFuncionario>();
        }
    
        public decimal codigoFuncionario { get; set; }
        public string nombre { get; set; }
        public System.DateTime fchNacimiento { get; set; }
        public Nullable<decimal> idClub { get; set; }
        public string foto { get; set; }
        public string usuarioCreacion { get; set; }
        public string usuarioModificacion { get; set; }
        public System.DateTime fchCreacion { get; set; }
        public Nullable<System.DateTime> fchModificacion { get; set; }
    
        public virtual Club Club { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato> Contrato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CorreoxFuncionario> CorreoxFuncionario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DireccionxFuncionario> DireccionxFuncionario { get; set; }
        public virtual Entrenador Entrenador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FuncionarioXClubXTorneo> FuncionarioXClubXTorneo { get; set; }
        public virtual Jugador Jugador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oferta> Oferta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TelefonoxFuncionario> TelefonoxFuncionario { get; set; }
    }
}
