//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fifa19.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FootballEntities : DbContext
    {
        public FootballEntities()
            : base("name=FootballEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Arbitro> Arbitro { get; set; }
        public virtual DbSet<ArbitroxPartido> ArbitroxPartido { get; set; }
        public virtual DbSet<ArbitroxPartidoHistorico> ArbitroxPartidoHistorico { get; set; }
        public virtual DbSet<CambioxPartido> CambioxPartido { get; set; }
        public virtual DbSet<CambioxPartidoHistorico> CambioxPartidoHistorico { get; set; }
        public virtual DbSet<Club> Club { get; set; }
        public virtual DbSet<Competicion> Competicion { get; set; }
        public virtual DbSet<Contrato> Contrato { get; set; }
        public virtual DbSet<CorreoxFuncionario> CorreoxFuncionario { get; set; }
        public virtual DbSet<DireccionxFuncionario> DireccionxFuncionario { get; set; }
        public virtual DbSet<Entrenador> Entrenador { get; set; }
        public virtual DbSet<Especialidad> Especialidad { get; set; }
        public virtual DbSet<EspecialidadxJugador> EspecialidadxJugador { get; set; }
        public virtual DbSet<FechaTorneo> FechaTorneo { get; set; }
        public virtual DbSet<FechaTorneoHistorico> FechaTorneoHistorico { get; set; }
        public virtual DbSet<Federacion> Federacion { get; set; }
        public virtual DbSet<Funcionario> Funcionario { get; set; }
        public virtual DbSet<FuncionarioXClubXTorneo> FuncionarioXClubXTorneo { get; set; }
        public virtual DbSet<FuncionarioXClubXTorneoHistorico> FuncionarioXClubXTorneoHistorico { get; set; }
        public virtual DbSet<GolxPartido> GolxPartido { get; set; }
        public virtual DbSet<GolxPartidoHistorico> GolxPartidoHistorico { get; set; }
        public virtual DbSet<Jugador> Jugador { get; set; }
        public virtual DbSet<JugadorxPartido> JugadorxPartido { get; set; }
        public virtual DbSet<JugadorxPartidoHistorico> JugadorxPartidoHistorico { get; set; }
        public virtual DbSet<Oferta> Oferta { get; set; }
        public virtual DbSet<Partido> Partido { get; set; }
        public virtual DbSet<PartidoHistorico> PartidoHistorico { get; set; }
        public virtual DbSet<Socio> Socio { get; set; }
        public virtual DbSet<SocioxClub> SocioxClub { get; set; }
        public virtual DbSet<TelefonoxFuncionario> TelefonoxFuncionario { get; set; }
        public virtual DbSet<TituloxEntrenador> TituloxEntrenador { get; set; }
        public virtual DbSet<Torneo> Torneo { get; set; }
        public virtual DbSet<TorneoHistorico> TorneoHistorico { get; set; }
        public virtual DbSet<TorneoXClub> TorneoXClub { get; set; }
        public virtual DbSet<TorneoXClubHistorico> TorneoXClubHistorico { get; set; }
    }
}
