//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fifa19.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Partido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partido()
        {
            this.ArbitroxPartido = new HashSet<ArbitroxPartido>();
            this.CambioxPartido = new HashSet<CambioxPartido>();
            this.GolxPartido = new HashSet<GolxPartido>();
            this.JugadorxPartido = new HashSet<JugadorxPartido>();
        }
    
        public decimal idPartido { get; set; }
        public decimal idCompeticion { get; set; }
        public decimal anho { get; set; }
        public decimal nroFecha { get; set; }
        public decimal equipoVisita { get; set; }
        public decimal equipoCasa { get; set; }
        public System.DateTime fecha { get; set; }
        [DisplayFormat(DataFormatString = "{0:N0}", ApplyFormatInEditMode = true)]
        public decimal golesCasa { get; set; }
        [DisplayFormat(DataFormatString = "{0:N0}", ApplyFormatInEditMode = true)]
        public decimal golesVisita { get; set; }
        public string usuarioCreacion { get; set; }
        public string usuarioModificacion { get; set; }
        public System.DateTime fchCreacion { get; set; }
        public Nullable<System.DateTime> fchModificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArbitroxPartido> ArbitroxPartido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CambioxPartido> CambioxPartido { get; set; }
        public virtual Club Club { get; set; }
        public virtual Club Club1 { get; set; }
        public virtual FechaTorneo FechaTorneo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GolxPartido> GolxPartido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JugadorxPartido> JugadorxPartido { get; set; }
    }
}
